from fastapi import APIRouter


router = APIRouter(tags=["demo"])


DEMO_WORKSPACE = {
    "student": {
        "name": "Demo Student",
        "timezone": "America/Chicago",
    },
    "courses": [
        {
            "id": "cse-3310",
            "code": "CSE 3310",
            "name": "Algorithms",
            "color": "#3B82F6",
        },
        {
            "id": "math-2425",
            "code": "MATH 2425",
            "name": "Calculus III",
            "color": "#8B5CF6",
        },
        {
            "id": "chem-3315",
            "code": "CHEM 3315",
            "name": "Analytical Chemistry",
            "color": "#10B981",
        },
    ],
    "sources": [
        {
            "id": "source-algorithms-syllabus",
            "course_id": "cse-3310",
            "type": "syllabus",
            "title": "CSE 3310 Syllabus",
            "received_at": "2026-09-01T09:00:00-05:00",
        },
        {
            "id": "source-algorithms-announcement",
            "course_id": "cse-3310",
            "type": "instructor_announcement",
            "title": "Quiz 2 schedule update",
            "received_at": "2026-09-12T09:20:00-05:00",
        },
        {
            "id": "source-calculus-email",
            "course_id": "math-2425",
            "type": "instructor_email",
            "title": "Exam 1 clarification",
            "received_at": "2026-09-12T08:10:00-05:00",
        },
        {
            "id": "source-chemistry-announcement",
            "course_id": "chem-3315",
            "type": "instructor_announcement",
            "title": "GC-MS lab report extension",
            "received_at": "2026-09-12T10:00:00-05:00",
        },
    ],
    "events": [
        {
            "id": "event-quiz-2",
            "course_id": "cse-3310",
            "type": "quiz",
            "title": "Quiz 2",
            "starts_at": "2026-09-17T08:00:00-05:00",
            "due_at": "2026-09-17T23:59:00-05:00",
            "status": "updated",
            "approved": False,
            "workload_minutes": 90,
            "source_id": "source-algorithms-announcement",
            "source_excerpt": "Quiz 2 has been moved from Tuesday to Thursday, September 17. It will remain available in Canvas from 8:00 AM to 11:59 PM.",
            "history": [
                {
                    "due_at": "2026-09-15T23:59:00-05:00",
                    "source_id": "source-algorithms-syllabus",
                    "reason": "Original syllabus schedule",
                    "is_current": False,
                },
                {
                    "due_at": "2026-09-17T23:59:00-05:00",
                    "source_id": "source-algorithms-announcement",
                    "reason": "Instructor announcement explicitly rescheduled Quiz 2",
                    "is_current": True,
                },
            ],
        },
        {
            "id": "event-assignment-2",
            "course_id": "cse-3310",
            "type": "assignment",
            "title": "Programming Assignment 2",
            "starts_at": None,
            "due_at": "2026-09-18T23:59:00-05:00",
            "status": "verified",
            "approved": False,
            "workload_minutes": 420,
            "source_id": "source-algorithms-announcement",
            "source_excerpt": "Programming Assignment 2 is still due Friday at 11:59 PM. Please start the assignment early; expected work time is 6-8 hours.",
            "history": [],
        },
        {
            "id": "event-midterm",
            "course_id": "cse-3310",
            "type": "exam",
            "title": "Midterm Exam",
            "starts_at": "2026-09-23T19:00:00-05:00",
            "due_at": "2026-09-23T21:00:00-05:00",
            "status": "verified",
            "approved": False,
            "workload_minutes": 300,
            "source_id": "source-algorithms-syllabus",
            "source_excerpt": "Midterm Exam - Wednesday, September 23, 7:00 PM",
            "history": [],
        },
        {
            "id": "event-calculus-review",
            "course_id": "math-2425",
            "type": "review",
            "title": "Exam 1 Review Session",
            "starts_at": "2026-09-17T17:00:00-05:00",
            "due_at": "2026-09-17T18:00:00-05:00",
            "status": "verified",
            "approved": False,
            "workload_minutes": 60,
            "source_id": "source-calculus-email",
            "source_excerpt": "A review session will be held Thursday at 5 PM.",
            "history": [],
        },
        {
            "id": "event-calculus-exam",
            "course_id": "math-2425",
            "type": "exam",
            "title": "Exam 1",
            "starts_at": "2026-09-18T18:00:00-05:00",
            "due_at": "2026-09-18T20:00:00-05:00",
            "location": "PKH 102",
            "status": "verified",
            "approved": False,
            "workload_minutes": 300,
            "source_id": "source-calculus-email",
            "source_excerpt": "Exam 1 is Friday, September 18, from 6:00 PM to 8:00 PM in PKH 102.",
            "history": [],
        },
        {
            "id": "event-gcms-report",
            "course_id": "chem-3315",
            "type": "lab",
            "title": "GC-MS Lab Report",
            "starts_at": None,
            "due_at": "2026-09-21T17:00:00-05:00",
            "status": "updated",
            "approved": False,
            "workload_minutes": 240,
            "source_id": "source-chemistry-announcement",
            "source_excerpt": "The GC-MS lab report deadline is extended from Sunday to Monday, September 21 at 5:00 PM.",
            "history": [
                {
                    "due_at": "2026-09-20T17:00:00-05:00",
                    "source_id": "source-chemistry-announcement",
                    "reason": "Original deadline referenced in extension notice",
                    "is_current": False,
                },
                {
                    "due_at": "2026-09-21T17:00:00-05:00",
                    "source_id": "source-chemistry-announcement",
                    "reason": "Deadline extension",
                    "is_current": True,
                },
            ],
        },
        {
            "id": "event-chem-prelab",
            "course_id": "chem-3315",
            "type": "lab",
            "title": "GC-MS Pre-Lab Worksheet",
            "starts_at": None,
            "due_at": None,
            "status": "needs_review",
            "approved": False,
            "workload_minutes": 60,
            "source_id": "source-chemistry-announcement",
            "source_excerpt": "Pre-lab worksheets are still due before your lab section begins.",
            "needs_review_reason": "Lab-section meeting time is unavailable, so DueScope cannot safely determine the due time.",
            "history": [],
        },
    ],
    "changes": [
        {
            "event_id": "event-quiz-2",
            "kind": "rescheduled",
            "message": "Quiz 2 moved from Tuesday, Sept. 15 to Thursday, Sept. 17.",
        },
        {
            "event_id": "event-gcms-report",
            "kind": "extended",
            "message": "GC-MS Lab Report extended to Monday, Sept. 21 at 5:00 PM.",
        },
        {
            "event_id": "event-chem-prelab",
            "kind": "needs_review",
            "message": "GC-MS Pre-Lab Worksheet needs a lab-section time before it can be added to a calendar.",
        },
    ],
    "workload": [
        {
            "date": "2026-09-17",
            "minutes": 150,
            "level": "normal",
            "reason": "Quiz 2 and Calculus review session",
        },
        {
            "date": "2026-09-18",
            "minutes": 720,
            "level": "high",
            "reason": "Programming Assignment 2 is due and Calculus Exam 1 runs from 6:00 PM to 8:00 PM.",
        },
        {
            "date": "2026-09-21",
            "minutes": 240,
            "level": "normal",
            "reason": "GC-MS Lab Report due at 5:00 PM",
        },
    ],
    "proposals": [],
    "job_applications": [],
    "job_calendar_proposals": [],
}


@router.get("/demo/workspace")
def get_demo_workspace() -> dict:
    return DEMO_WORKSPACE